INSERT INTO CURRENCY_EXCHANGE  (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,ENVIRONMENT)
VALUES(1001,'USD','INR',78,'');
INSERT INTO CURRENCY_EXCHANGE  (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,ENVIRONMENT)
VALUES(1002,'EUR','INR',89,'');
INSERT INTO CURRENCY_EXCHANGE  (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,ENVIRONMENT)
VALUES(1003,'AUD','INR',65,'');
INSERT INTO CURRENCY_EXCHANGE  (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,ENVIRONMENT)
VALUES(1004,'BD','INR',11,'');